# This is a basic workflow to help you get started with Actions

name: Klog.Backend.Workflows

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: build&deploy

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn
      - name: Build
        run: yarn build

      - name: deploy file to server
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: '${{ secrets.PRODUCTION_SERVER_USER_NAME}}'
          server: '${{ secrets.PRODUCTION_SERVER_IP }}'
          ssh_private_key: '${{ secrets.PRODUCTION_SSH_PRIVATE_KEY }}'
          local_path: './dist/*'
          remote_path: '/home/ubuntu/klog.backend/dist'
          args: '-o ConnectTimeout=5'

      - name: server down
        run: sudo pm2 kill

      - name: server start
        run: sudo yarn start:prod
